### ISSUE TITLE
Using submodule interface for snow is a royal pain

### ISSUE THREAD

**Issue by barryfm** [ashinn/chibi-snow#1] opened 2015-03-22 13:39 UTC
I think submodules are useful when a library is needed to build a package, but is separately managed so that you need to protect against updates that break the root package.  Snow isn't separately managed.  This is more reasonable for something like a gnulib or libgc dependency, where the package can usually be built using the platforms supplied libraries.  But if there are any incompatiiblities, the submodules can be cloned, and will be found and used instead.  Submodules are more a workaround than a feature.

Submodules are otherwise just an inconvience which requires a seperate 'git submodule update".  The .gitmodules file in chibi-snow references it via ssh, so that a ssh fetch of it is performed.  When someone has cloned the library using git: or https: protocols this causes an inconsistancy which just makes the chance of failure greater.  Even if github allows it for general connections it may not be usable from everywhere chibi-scheme may be cloned.

Right now the chibi-scheme install script fails if snow isn't present.  It seems that chibi should otherwise be installable without snow.

Snow could be detatched from chibi-scheme and have its own Makefile that installs it on top of an exisiting chibi-scheme distribution.  If could then have its subdirectories layed out in a way which makes it possible to develop separately, such as including other scheme implementations.

Otherwise I think it would be better just left as part of the chibi-scheme repo.

**Comment by ilammy** [comment] 2015-03-27 23:15
Seconding this. I am currently trying to move the current CI system of my own libs to fetch Chibi from Github instead of old Google Code repo; and kinda fail at that because I have very little experience with submodules. Disregaring the experience, personally I think that mirroring nearly every commit to chibi-snow with an 'Updating submodules' in chibi-scheme is dumb.

I would either move Snow back into Chibi's core repo (the easy way), or completely separate them (the proper one). I believe that Snow should be able to bootstrap itself. Will try to do this in the nearest time as I am interested in getting my CI stuff up.

Installation then could be something like this

```
wget https://raw.githubusercontent.com/ashinn/chibi-install/master/install-chibi.sh
chmod +x install-chibi.sh
./install-chibi.sh
```

which does whatever magic is required to build the intended 'installation package'. This will not be much different from the 'everything in a single repo' way:

```
git clone https://github.com/ashinn/chibi-scheme
cd chibi-scheme
make && make install
```

Well, _ideally_, if I am allowed to dream a bit, I would prefer just

```
aptitude install chibi-scheme
```

**Comment by ilammy** [comment] 2015-03-28 20:41
Okay... so here's what I got.

The commits that do the thing:

```
git://github.com/ilammy/chibi-scheme.git separate-snow
git://github.com/ilammy/chibi-snow.git   separate-snow
```

Snow is entriely removed from Chibi and is wrapped into a self-installable snowball. [It actually works](https://travis-ci.org/ilammy/srfi-60/builds/56233171) (nevermind the test failure, it's due to bugs in Chibi, look at _install_ steps).

Snow is now laid out in the following way, to be able to easily pack it into a snowball.

```
.
├── bootstrap.sh
├── chibi-snow
│   ├── bin
│   │   └── snow-chibi
│   ├── chibi
│   │   └── snow
│   │       ├── commands.scm
│   │       ├── commands.sld
│   │       ├── fort.scm
│   │       ├── fort.sld
│   │       ├── interface.scm
│   │       ├── interface.sld
│   │       ├── package.scm
│   │       ├── package.sld
│   │       ├── utils.scm
│   │       └── utils.sld
│   └── package.scm
└── README.md
```

It is _not_ a part of initial Chibi clone, it has to be cloned and installed separately with the `bootstrap.sh` script after Chibi is installed.

@ashinn, any ideas, suggestions, threats?

**Comment by ashinn** [comment] 2015-03-29 05:21
The bootstrapping is nice, but I don't want people to have
to even make that much more effort.  The default chibi install
should have everything you need to get all additional packages.
This includes the distributed tarballs, plus any other bundles
such as for Debian, etc.

There's also currently no motivation, since snow-chibi isn't
portable yet.  When and if we get ports to other implementations
we can consider splitting the modules, but even then I consider
it unlikely.  You're trying to make things easier for snow developers
at the expense of the end-user programmers.

For now I'll just move everything back into one repo.

**Comment by ilammy** [comment] 2015-03-29 09:24
That's fine to me either.

On the second thought, I realized that moving it out was intended to make Snow more portable. But, meh, it's a package manager _for Chibi_. So it makes sense to keep it right there, it's not that bulky.

(And, personally for me, it even makes sense to keep Chibi Snow _not_ portable as I am not a fan of portability of end-user applications via a thousand of cond-expands into non-portable code, as [Snow2](https://github.com/sethalves/snow2-client) does. It's better to limit cond-expands to libraries, and if you have many of them in your library it's better to push for a SRFI.)

**Comment by ashinn** [comment] 2015-04-04 14:18
Reverted to a single module.

**Closed as completed by ashinn** 2015-04-04 14:18 UTC
